### ISSUE TITLE
Problem when autoscrolling immediately after scene load.

### ISSUE THREAD

**Issue by yzaroui** [setchi/FancyScrollView#11] opened 2017-10-30 08:44 UTC
Hello,

I am working on this game : https://play.google.com/store/apps/details?id=com.Meludia.MicroMelody and used FancyScrollView to display game levels.
I have a scene for selecting game worlds then a scene for displaying levels from the selected world.
The levels scene must scroll the last played level. But when it scrolls it has strange behaviours, please see attached images and video.

![missingcenter](https://user-images.githubusercontent.com/3058420/32161083-9c5f4d3e-bd54-11e7-9957-044bbf515903.png)
![missingleft](https://user-images.githubusercontent.com/3058420/32161086-9f5eaf3e-bd54-11e7-96d2-2c16a8494017.png)
https://www.dropbox.com/s/s622j1wp5dzjvu5/Meludia_2017-10-30-09-37-40.mp4?dl=0

**Comment by setchi** [comment] 2017-10-30 09:15
Thank you for the report

Please try the following
- Redraw the cell by calling the FancyScrollView.UpdateContents () method
- If Active / Inactive of Cell is dynamically switched, Acquire Animator's normalizedTime with OnDisable () and restore its position when OnEnable ()
- Update FancyScrollView to the latest version

**Comment by setchi** [comment] 2017-10-30 09:27
It is probably due to the behavior of Unity's Animator behavior.

**Comment by yzaroui** [comment] 2017-10-30 10:48
Here is how I do
```
public void UpdateData(List<GameMenuCellData> data, int activeCellIndex = 0)
{
    cellData = data;
    scrollPositionController.SetDataCount(cellData.Count);
    UpdateContents();
    scrollPositionController.ScrollTo(activeCellIndex, 0.4f);
}
```

Now if I change the duration to 2 seconds, the problem goes, but the scrolling is too slow :
`scrollPositionController.ScrollTo(activeCellIndex, 0.4f);`

I think that when I load the scene, the scroll starts animating before the scene is visible and when the 0.4 seconds are elapsed, the scroll stops even if the component is not in a stable situation.

Do you have any other method the fix this?
Best,

**Comment by setchi** [comment] 2017-10-30 12:15
Because I do not reproduce in my environment, I may not be able to give useful advice
How about calling UpdateData () after waiting until the scene is loaded?

**Comment by setchi** [comment] 2018-02-07 14:49
I will close it once.
Please contact me if there is something again.

**Closed as completed by setchi** 2018-02-07 14:49 UTC
